version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
    groups:
      build-tooling:
        patterns:
          - "com.vanniktech.maven.publish"
          - "org.junit:*"
          - "org.springframework:*"
          - "org.springframework.boot:*"
          - "io.grpc:*"
          - "com.google.api.grpc:*"
          - "com.google.protobuf:*"

  - package-ecosystem: gradle
    directory: /smoke-test-kotlin
    schedule:
      interval: weekly

  - package-ecosystem: maven
    directory: /smoke-test-maven-java
    schedule:
      interval: weekly

  - package-ecosystem: maven
    directory: /smoke-test-maven-kotlin
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"
