version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      gradle-dependencies:
        patterns: ["*"]
  - package-ecosystem: gradle
    directory: "/smoke-test"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 3
    groups:
      smoke-gradle-dependencies:
        patterns: ["*"]
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns: ["*"]
