GROUP=io.github.aalsanie
POM_ARTIFACT_ID=codes
VERSION_NAME=0.3.1
POM_NAME=Codes
POM_DESCRIPTION=Stable application outcomes, structured issues, and explicit protocol mappings for Java and Kotlin.
POM_INCEPTION_YEAR=2026
POM_URL=https://github.com/aalsanie/codes
POM_LICENSE_NAME=The Apache License, Version 2.0
POM_LICENSE_URL=https://www.apache.org/licenses/LICENSE-2.0.txt
POM_LICENSE_DIST=repo
POM_SCM_URL=https://github.com/aalsanie/codes
POM_SCM_CONNECTION=scm:git:git://github.com/aalsanie/codes.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/aalsanie/codes.git
POM_DEVELOPER_ID=aalsanie
POM_DEVELOPER_NAME=Ahmad Al-sanie
POM_DEVELOPER_URL=https://github.com/aalsanie
junitVersion=6.1.3
springFrameworkVersion=7.0.9
springBootVersion=4.1.1
grpcVersion=1.83.1
protoGoogleCommonProtosVersion=2.75.0
protobufVersion=4.33.6
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.parallel=true
